### ISSUE TITLE
How can I train model or already trained ?

### ISSUE THREAD

**Issue by arslonbeksaidov** [YashShende/Pneumonia_Detection#1]
Hello, your work is good, but documentation is not enough, can you tell us where images should be uploaded ?

**Comment by YashShende** [comment]
Hi Arslon, Actually I already trained the model using the Kaggle Data set
on the GoogleColab and I just uploaded the trained model file on GitHub to
keep things simple.my main motivation is to opensource the web interface in
which you just replace the model and ready to deploy.if you want to take
look at how I trained my model use this link: https://del.dog/minip

**Comment by arslonbeksaidov** [comment]
Fine
